[project]
name = "pktparsers"
version = "1.0.0"
description = "Extensible framework for dissecting and creating protocol packets and parsers."
readme = "README.md"
requires-python = ">=3.12"

authors = [
    { name = "Gustavo Araújo" }
]

dependencies = [
    "dpkt==1.9.8",
    "textual==6.2.1",
    "rich==14.3.3",
    "argcomplete",
    "cli-core @ git+https://github.com/gusprojects008/cli-core.git@v1.0.0"
]

keywords = [
    "engine",
    "framework",
    "parsers",
    "dissection",
    "dissectors",
    "network",
    "sniffer",
    "packets",
    "ethernet",
    "wifi",
    "bluetooth",
    "security"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
    "Topic :: System :: Networking",
    "Topic :: Security"
]

[project.scripts]
pktparsers = "pktparsers.cli.main:main"
pktparsers-tui = "pktparsers.tui.main:main"

[tool.setuptools.packages.find]
include = ["pktparsers*"]
