ASSOCIATION_REQUEST = 0
ASSOCIATION_RESPONSE = 1
REASSOCIATION_REQUEST = 2
REASSOCIATION_RESPONSE = 3
PROBE_REQUEST = 4
PROBE_RESPONSE = 5
TIMING_ADVERTISEMENT = 6
BEACON = 8
ATIM = 9
DISASSOCIATION = 10
AUTHENTICATION = 11
DEAUTHENTICATION = 12
ACTION = 13
ACTION_NO_ACK = 14

SUBTYPES_NAMES = {
    ASSOCIATION_REQUEST: "Association Request",
    ASSOCIATION_RESPONSE: "Association Response",
    REASSOCIATION_REQUEST: "Reassociation Request",
    REASSOCIATION_RESPONSE: "Reassociation Response",
    PROBE_REQUEST: "Probe Request",
    PROBE_RESPONSE: "Probe Response",
    TIMING_ADVERTISEMENT: "Timing Advertisement",
    BEACON: "Beacon",
    ATIM: "ATIM",
    DISASSOCIATION: "Disassociation",
    AUTHENTICATION: "Authentication",
    DEAUTHENTICATION: "Deauthentication",
    ACTION: "Action",
    ACTION_NO_ACK: "Action No Ack",
}
