FC = "fc"
PROTOCOL_VERSION = "protocol_version"
TYPE = "type"
TYPE_NAME = "type_name"
SUBTYPE = "subtype"
SUBTYPE_NAME = "subtype_name"
TO_DS = "tods"
FROM_DS = "fromds"
PROTECTED = "protected"
DURATION_ID = "duration_id"
RA = "ra"
TA = "ta"
SA = "sa"
DA = "da"
SEQUENCE_NUMBER = "sequence_number"
QOS_CONTROL = "qos_control"
BSSID = "bssid"

DURATION_FMT = "<H"
FS_FMT = "<H"
QOS_CONTROL_FMT = "<H"
FC_FMT = "<H"
FMT = FC_FMT

