from .definitions.dlt import *

ERF_TYPE_LEGACY  = 0
ERF_TYPE_HDLC_POS = 2
ERF_TYPE_ETH = 3
ERF_TYPE_ATM = 4
ERF_TYPE_AAL5 = 5
ERF_TYPE_MC_HDLC = 7
ERF_TYPE_MC_RAW = 8
ERF_TYPE_MC_ATM = 9
ERF_TYPE_MC_AAL5 = 10
ERF_TYPE_COLOR_HDLC_POS = 16
ERF_TYPE_COLOR_ETH = 17
ERF_TYPE_MC_AAL2 = 19
ERF_TYPE_IP_COUNTER = 20
ERF_TYPE_IPV4 = 21
ERF_TYPE_IPV6 = 22
ERF_TYPE_RESERVED_23 = 23
ERF_TYPE_RAW_LINK = 24
ERF_TYPE_INFINIBAND = 25
ERF_TYPE_IPC = 26
ERF_TYPE_TUNNEL_IP = 27
ERF_TYPE_CLASSIFICATION = 28
ERF_TYPE_PASSIVE_CONTAINER = 29
ERF_TYPE_ETHERNET_SGMII = 30
ERF_TYPE_PROVENANCE = 31
ERF_TYPE_FIBRE_CHANNEL = 32
ERF_TYPE_I2C = 33
ERF_TYPE_LORA = 34
ERF_TYPE_COEX = 35
ERF_TYPE_GENERIC_METADATA = 36
ERF_TYPE_UTMI = 37
ERF_TYPE_MISC_METADATA = 38
ERF_TYPE_AAL5_INTERLEAVE = 39
ERF_TYPE_P2P_DECAP = 40
ERF_TYPE_EPON_ONU = 41
ERF_TYPE_EPON_OLT = 42
ERF_TYPE_EMULATED_CHANNEL = 43
ERF_EXTENSION_MASK = 0x80

ERF_TYPE_TO_DLT = {
    ERF_TYPE_HDLC_POS: DLT_HDLC,
    ERF_TYPE_ETH: DLT_EN10MB,
    ERF_TYPE_ATM: DLT_ATM_RFC1483,
    ERF_TYPE_AAL5: DLT_ATM_RFC1483,
    ERF_TYPE_MC_HDLC: DLT_HDLC,
    ERF_TYPE_MC_RAW: DLT_RAW,
    ERF_TYPE_MC_ATM: DLT_ATM_RFC1483,
    ERF_TYPE_MC_AAL5: DLT_ATM_RFC1483,
    ERF_TYPE_COLOR_HDLC_POS: DLT_HDLC,
    ERF_TYPE_COLOR_ETH: DLT_EN10MB,
    ERF_TYPE_IPV4: DLT_IPV4,
    ERF_TYPE_IPV6: DLT_IPV6,
    ERF_TYPE_RAW_LINK: DLT_RAW,
    ERF_TYPE_TUNNEL_IP: DLT_RAW,
    ERF_TYPE_ETHERNET_SGMII: DLT_EN10MB,
}
