MGMT = 0
CTRL = 1
DATA = 2

FRAME_TYPES = {
    MGMT: "Management",
    CTRL: "Control",
    DATA: "Data",
}

MGMT_ASSOCIATION_REQUEST = 0
MGMT_ASSOCIATION_RESPONSE = 1
MGMT_REASSOCIATION_REQUEST = 2
MGMT_REASSOCIATION_RESPONSE = 3
MGMT_PROBE_REQUEST = 4
MGMT_PROBE_RESPONSE = 5
MGMT_TIMING_ADVERTISEMENT = 6
MGMT_BEACON = 8
MGMT_ATIM = 9
MGMT_DISASSOCIATION = 10
MGMT_AUTHENTICATION = 11
MGMT_DEAUTHENTICATION = 12
MGMT_ACTION = 13
MGMT_ACTION_NO_ACK = 14

CTRL_BLOCK_ACK_REQUEST = 8
CTRL_BLOCK_ACK = 9
CTRL_PS_POLL = 10
CTRL_RTS = 11
CTRL_CTS = 12
CTRL_ACK = 13
CTRL_CF_END = 14
CTRL_CF_END_ACK = 15

DATA_DATA = 0
DATA_DATA_CF_ACK = 1
DATA_DATA_CF_POLL = 2
DATA_DATA_CF_ACK_CF_POLL = 3
DATA_NULL = 4
DATA_CF_ACK = 5
DATA_CF_POLL = 6
DATA_CF_ACK_CF_POLL = 7
DATA_QOS_DATA = 8
DATA_QOS_DATA_CF_ACK = 9
DATA_QOS_DATA_CF_POLL = 10
DATA_QOS_DATA_CF_ACK_CF_POLL = 11
DATA_QOS_NULL = 12
DATA_RESERVED = 13
DATA_QOS_CF_POLL = 14
DATA_QOS_CF_ACK_CF_POLL = 15

NULL_DATA_SUBTYPES = [
    DATA_NULL,
    DATA_CF_ACK,
    DATA_CF_POLL,
    DATA_CF_ACK_CF_POLL,
    DATA_QOS_NULL,
    DATA_RESERVED,
    DATA_QOS_CF_POLL,
    DATA_QOS_CF_ACK_CF_POLL
]

FRAME_SUBTYPES = {
    MGMT: {
        MGMT_ASSOCIATION_REQUEST: "Association Request",
        MGMT_ASSOCIATION_RESPONSE: "Association Response",
        MGMT_REASSOCIATION_REQUEST: "Reassociation Request",
        MGMT_REASSOCIATION_RESPONSE: "Reassociation Response",
        MGMT_PROBE_REQUEST: "Probe Request",
        MGMT_PROBE_RESPONSE: "Probe Response",
        MGMT_TIMING_ADVERTISEMENT: "Timing Advertisement",
        MGMT_BEACON: "Beacon",
        MGMT_ATIM: "ATIM",
        MGMT_DISASSOCIATION: "Disassociation",
        MGMT_AUTHENTICATION: "Authentication",
        MGMT_DEAUTHENTICATION: "Deauthentication",
        MGMT_ACTION: "Action",
        MGMT_ACTION_NO_ACK: "Action No Ack",
    },
    CTRL: {
        CTRL_BLOCK_ACK_REQUEST: "Block Ack Request",
        CTRL_BLOCK_ACK: "Block Ack",
        CTRL_PS_POLL: "PS-Poll",
        CTRL_RTS: "RTS",
        CTRL_CTS: "CTS",
        CTRL_ACK: "ACK",
        CTRL_CF_END: "CF-End",
        CTRL_CF_END_ACK: "CF-End+CF-Ack",
    },
    DATA: {
        DATA_DATA: "Data",
        DATA_DATA_CF_ACK: "Data+CF-Ack",
        DATA_DATA_CF_POLL: "Data+CF-Poll",
        DATA_DATA_CF_ACK_CF_POLL: "Data+CF-Ack+CF-Poll",
        DATA_NULL: "Null",
        DATA_CF_ACK: "CF-Ack",
        DATA_CF_POLL: "CF-Poll",
        DATA_CF_ACK_CF_POLL: "CF-Ack+CF-Poll",
        DATA_QOS_DATA: "QoS Data",
        DATA_QOS_DATA_CF_ACK: "QoS Data+CF-Ack",
        DATA_QOS_DATA_CF_POLL: "QoS Data+CF-Poll",
        DATA_QOS_DATA_CF_ACK_CF_POLL: "QoS Data+CF-Ack+CF-Poll",
        DATA_QOS_NULL: "QoS Null",
        DATA_RESERVED: "Reserved",
        DATA_QOS_CF_POLL: "QoS CF-Poll",
        DATA_QOS_CF_ACK_CF_POLL: "QoS CF-Ack+CF-Poll",
    },
}

RSN_CIPHER_WEP40 = 1
RSN_CIPHER_TKIP = 2
RSN_CIPHER_CCMP = 4
RSN_CIPHER_WEP104 = 5
RSN_CIPHER_GCMP = 8
RSN_CIPHER_GCMP_256 = 9
RSN_CIPHER_CCMP_256 = 10
RSN_CIPHER_BIP_GMAC_128 = 11
RSN_CIPHER_BIP_GMAC_256 = 12
RSN_CIPHER_BIP_CMAC_256 = 13
RSN_AKM_8021X = 1
RSN_AKM_PSK = 2
RSN_AKM_FT_8021X = 3
RSN_AKM_FT_PSK = 4
RSN_AKM_8021X_SHA256 = 5
RSN_AKM_PSK_SHA256 = 6
RSN_AKM_TDLS = 7
RSN_AKM_SAE = 8
RSN_AKM_FT_SAE = 9
RSN_AKM_AP_PEERKEY = 10
RSN_AKM_SUITE_B_8021X = 11
RSN_AKM_SUITE_B_192_8021X = 12
RSN_AKM_FILS_SHA256 = 14
RSN_AKM_FILS_SHA384 = 15
RSN_AKM_OWE = 18

RSN_MIN_LEN = 2
RSN_GROUP_CIPHER_LEN = 4
RSN_SUITE_LEN = 4

IEEE80211_FCS_LEN = 4

MIN_IE_LEN = 2
