from core.common.parser import size_to_struct_fmt

EAPOL_KEY_REPLAY_COUNTER_LENGTH = 8
EAPOL_KEY_NONCE_LENGTH = 32
EAPOL_KEY_IV_LENGTH = 16
EAPOL_KEY_RSC_LENGTH = 8
EAPOL_KEY_ID_LENGTH = 8
EAPOL_KEY_MIC_LENGTH = 16
EAPOL_KEY_DATA_LENGTH_FIELD = 2
EAPOL_KEY_DATA_LENGTH = size_to_struct_fmt(EAPOL_KEY_DATA_LENGTH_FIELD)
EAPOL_KEY_PMKID_LENGTH = 16
