from pktparsers.core.definitions import protocol as proto

ETHERTYPE_IPV4 = 0x0800
ETHERTYPE_ARP = 0x0806
ETHERTYPE_IPV6 = 0x86DD
ETHERTYPE_EAPOL = 0x888E
ETHERTYPE_WAPI = 0x88B4

ETHERTYPE_DISPATCH = {
    ETHERTYPE_IPV4:  proto.INET_IPV4,
    ETHERTYPE_IPV6:  proto.INET_IPV6,
    ETHERTYPE_EAPOL: proto.IEE802_EAPOL,
    ETHERTYPE_WAPI:  proto.WAPI,
    ETHERTYPE_ARP:   proto.ARP,
}
